"""
Core data models for the SkillForge multi-agent system.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ──────────────────────────────────────
# Enums
# ──────────────────────────────────────

class AgentRole(str, Enum):
    ORCHESTRATOR = "orchestrator"
    PLANNER = "planner"
    EXECUTOR = "executor"
    REVIEWER = "reviewer"
    RESEARCH = "research"
    CREATIVE = "creative"


class TaskStatus(str, Enum):
    PENDING = "pending"
    ASSIGNED = "assigned"
    EXECUTING = "executing"
    REVIEWING = "reviewing"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class MessageType(str, Enum):
    TASK_ASSIGNMENT = "task_assignment"
    RESULT = "result"
    FEEDBACK = "feedback"
    ESCALATION = "escalation"
    SYSTEM = "system"


class SkillCategory(str, Enum):
    DOCUMENT = "document"
    EMAIL = "email"
    DATA = "data"
    SCHEDULE = "schedule"
    PRESENTATION = "presentation"
    HR = "hr"
    TRANSLATION = "translation"
    AUTOMATION = "automation"
    KNOWLEDGE = "knowledge"
    OTHER = "other"


class FieldType(str, Enum):
    STRING = "string"
    NUMBER = "number"
    BOOLEAN = "boolean"
    ENUM = "enum"
    ARRAY = "array"
    OBJECT = "object"


class QualityVerdict(str, Enum):
    PASS = "pass"
    FAIL = "fail"
    WARN = "warn"


# ──────────────────────────────────────
# Skill Schema Models
# ──────────────────────────────────────

class SkillField(BaseModel):
    name: str
    type: FieldType = FieldType.STRING
    required: bool = False
    description: str = ""
    values: list[str] = Field(default_factory=list)  # for enum type
    default: Any = None


class SkillSettings(BaseModel):
    max_tokens: int = 2000
    temperature: float = 0.7
    model: str = "default"
    timeout_ms: int = 30000
    requires_review: bool = True


class SkillDefinition(BaseModel):
    """Complete skill definition as stored in the registry."""
    id: str
    name: str
    version: str = "1.0.0"
    author: str = "system"
    category: SkillCategory = SkillCategory.OTHER
    description: str = ""
    icon: str = "doc"

    inputs: list[SkillField] = Field(default_factory=list)
    outputs: list[SkillField] = Field(default_factory=list)

    prompt_template: str = ""
    settings: SkillSettings = Field(default_factory=SkillSettings)
    permissions: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)

    # Store metadata
    rating: float = 0.0
    downloads: int = 0
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


# ──────────────────────────────────────
# Skill Execution Models
# ──────────────────────────────────────

class SkillExecutionRequest(BaseModel):
    skill_id: str
    inputs: dict[str, Any] = Field(default_factory=dict)
    context: dict[str, Any] = Field(default_factory=dict)


class SkillExecutionResult(BaseModel):
    skill_id: str
    outputs: dict[str, Any] = Field(default_factory=dict)
    success: bool = True
    error: str | None = None
    tokens_used: int = 0
    execution_time_ms: int = 0
    resolved_prompt: str = ""


# ──────────────────────────────────────
# Agent Messages
# ──────────────────────────────────────

class AgentMessage(BaseModel):
    """Message passed between agents via the Context Bus."""
    message_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    from_agent: AgentRole
    to_agent: AgentRole | None = None
    type: MessageType = MessageType.TASK_ASSIGNMENT
    payload: dict[str, Any] = Field(default_factory=dict)
    context_ref: str = ""
    timestamp: datetime = Field(default_factory=datetime.utcnow)


# ──────────────────────────────────────
# Task / Plan Models
# ──────────────────────────────────────

class SubTask(BaseModel):
    """A single unit of work within a plan."""
    task_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    description: str
    agent_role: AgentRole
    skill_id: str | None = None
    skill_inputs: dict[str, Any] = Field(default_factory=dict)
    dependencies: list[str] = Field(default_factory=list)  # task_ids
    status: TaskStatus = TaskStatus.PENDING
    result: SkillExecutionResult | None = None
    priority: int = 1  # 1=highest


class ExecutionPlan(BaseModel):
    """A DAG of sub-tasks generated by the Planner."""
    plan_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    user_request: str
    tasks: list[SubTask] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    iteration: int = 1


# ──────────────────────────────────────
# Quality Review
# ──────────────────────────────────────

class ReviewItem(BaseModel):
    aspect: str
    verdict: QualityVerdict
    score: float = 0.0
    comment: str = ""


class QualityReview(BaseModel):
    review_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    task_id: str
    overall_score: float = 0.0
    passed: bool = False
    items: list[ReviewItem] = Field(default_factory=list)
    feedback: str = ""


# ──────────────────────────────────────
# Orchestration Result
# ──────────────────────────────────────

class OrchestrationResult(BaseModel):
    """Final output from the orchestration pipeline."""
    session_id: str
    user_request: str
    plan: ExecutionPlan | None = None
    final_output: str = ""
    agent_outputs: dict[str, Any] = Field(default_factory=dict)
    quality_review: QualityReview | None = None
    total_tokens: int = 0
    total_time_ms: int = 0
    iterations: int = 1
    success: bool = True
    error: str | None = None


# ──────────────────────────────────────
# Memory Models
# ──────────────────────────────────────

class ChatMessage(BaseModel):
    role: str  # user | assistant | system
    content: str
    agent: AgentRole | None = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class TokenBudget(BaseModel):
    used: int = 0
    limit: int = 128000
    compression_threshold: int = 100000


class WorkingMemoryState(BaseModel):
    """Current session state."""
    session_id: str
    user_id: str = "default"
    messages: list[ChatMessage] = Field(default_factory=list)
    active_agents: list[AgentRole] = Field(default_factory=list)
    skill_stack: list[dict[str, Any]] = Field(default_factory=list)
    shared_vars: dict[str, Any] = Field(default_factory=dict)
    token_budget: TokenBudget = Field(default_factory=TokenBudget)


class EpisodicEntry(BaseModel):
    """A single episodic memory record."""
    session_id: str
    summary: str
    skills_used: list[str] = Field(default_factory=list)
    outcome: str = "success"
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    metadata: dict[str, Any] = Field(default_factory=dict)


class SemanticEntry(BaseModel):
    """A single semantic memory record."""
    entry_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    content: str
    category: str = "general"
    embedding: list[float] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ──────────────────────────────────────
# API Models
# ──────────────────────────────────────

class UserRequest(BaseModel):
    message: str
    session_id: str | None = None
    user_id: str = "default"
    context: dict[str, Any] = Field(default_factory=dict)


class SkillValidationResult(BaseModel):
    valid: bool
    errors: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    checks_passed: int = 0
    checks_total: int = 0
